covid19/covid19/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('covidapp.urls'))
]

covid19/covidapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url


urlpatterns = [
    path('dev/',views.dev,name='dev'),
    path('',views.api,name='api'),
    path('global/',views.globalview,name='globalview'),
    path('india/',views.statewise,name='statewise'),
    path('india/<sname>/<scode>',views.stateview,name='stateview'),
    path('country/<code>/',views.countryview,name='countryview'),
    path('search/',views.statesearch,name='statesearch'),
    path('helpline/',views.Helpline,name='Helpline'),
    path('about/', views.about, name='about'),
    path('map/', views.map, name='map'),
    path('wiki/', views.wiki, name='wiki'),
    path('india/<sname>/<dname>/', views.districtview, name='districtview'),
    path('essentials/', views.essentials, name='essentials'),
    
    
]

covid19/covidapp/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone


# Create your models here.
class Suggestion(models.Model):
    suggestion = models.CharField(max_length = 400, default='',blank='true', null='true', verbose_name='Suggestions/Comments(if any)')
    email = models.EmailField(unique='true', verbose_name='Your Email', error_messages={'unique':"You have already reviewed. Thank you for the review!"})
    rating = models.IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)], default=1,)
    date_posted = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        return f"{self.email}, Rating : {self.rating}"

covid19/covidapp/forms.py
from django import forms
from .models import Suggestion

class SuggestionForm(forms.ModelForm):
    class Meta:
        model = Suggestion
        fields = ['suggestion', 'email', 'rating']

covid19/covidapp/views.py
from django.shortcuts import render,redirect,reverse,HttpResponse
from .models import Suggestion
from .forms import SuggestionForm
from django.contrib import messages
import geoip2.database

import datetime
from datetime import date
import calendar
import pytz
import requests
from operator import itemgetter
import json
from .models import Suggestion
import copy
from babel.numbers import format_currency

def globalview(request):
    d=datetime.datetime.now(pytz.timezone('Asia/Kolkata'))
    global_stats = requests.get('http://api.coronatracker.com/v3/stats/worldometer/global')
    global_timeline = requests.get('https://corona-api.com/timeline')
    global_timeline1 = global_timeline.json()
    global_timeline1 = global_timeline1['data']
    l= len(global_timeline1)
    l=l-1 
    global_timeline1 = global_timeline1[0:l:10]
    global_timeline1 = global_timeline1[::-1]

    global_stats = global_stats.json()
    last_updated = global_stats['created']
    del global_stats['totalCasesPerMillionPop']
    del global_stats['created']
    for x in global_stats:
        a = global_stats[x]
        b = format_currency(a, 'INR', locale='en_IN')
        c = b[1:len(b)-3]
        global_stats[x] = c
    all_country = requests.get('https://corona-api.com/countries')
    all_country = all_country.json()
    country_data = all_country['data']
    for x in country_data:
        x['total_confirmed'] = (x['latest_data']['confirmed'])    
    country_data = sorted(country_data, key=itemgetter('total_confirmed'),reverse=True)
    for x in country_data:
        total = x['latest_data']['confirmed']
        total = format_currency(total, 'INR', locale='en_IN')
        total = total[1:len(total)-3]
        x['latest_data']['confirmed'] = total
    data={
        'all_country':country_data ,
        '1':country_data[0],
        '2':country_data[1],
        '3':country_data[2],
        'global': global_stats,
        
        'globaltimeline': global_timeline1,
        'd':d,
        'last_updated':last_updated
       
        
    }
    return render(request,'covidapp/globalview.html',data)

def api(request):
    global_stats = requests.get('http://api.coronatracker.com/v3/stats/worldometer/global')
    global_stats = global_stats.json()
    
    del global_stats['totalCasesPerMillionPop']
    del global_stats['created']
    for x in global_stats:
        a = global_stats[x]
        b = format_currency(a, 'INR', locale='en_IN')
        c = b[1:len(b)-3]
        global_stats[x] = c
    all_country = requests.get('https://corona-api.com/countries')
    all_country = all_country.json()
    country_data = all_country['data']
    for x in country_data:
        x['total_confirmed'] = (x['latest_data']['confirmed'])    
    country_data = sorted(country_data, key=itemgetter('total_confirmed'),reverse=True)
    ranknumber = 1
    for x in country_data:
        x['rank'] = ranknumber
        ranknumber = ranknumber + 1
    country_total_data_commas = ['confirmed', 'deaths', 'recovered']
    country_daily_data_commas = ['confirmed', 'deaths']
    for x in country_data:
        for l in country_total_data_commas:
            total = x['latest_data'][l]
            total = format_currency(total, 'INR', locale='en_IN')
            total = total[1:len(total)-3]
            x['latest_data'][l] = total

    for x in country_data:
        for l in country_daily_data_commas:
            total = x['today'][l]
            total = format_currency(total, 'INR', locale='en_IN')
            total = total[1:len(total)-3]
            x['today'][l] = total

    response_india = requests.get('https://api.covid19india.org/data.json')
    india = response_india.json()
    
    
    state=india['statewise']
    india1_comma = ['active', 'confirmed', 'deaths','recovered' ,'deltaconfirmed', 'deltadeaths', 'deltarecovered', ]
    for x in state:
            for l in india1_comma:
                total = x[l]
                total = format_currency(total, 'INR', locale='en_IN')
                total = total[1:len(total)-3]
                x[l] = total
    state=list(state)
    newstate={}
    for entry in state:
        name = entry.pop('state')
        newstate[name] = entry
    # statelist=list(newstate)
    del newstate['Total']
    data={
        'all_country':country_data ,
        '1':country_data[0],
        '2':country_data[1],
        '3':country_data[2],
        'global': global_stats,
        'india_total':india['statewise'][0],
        'statelist':newstate,
        'india':india,
        
        
    }
    
    
    return render(request, 'covidapp/api.html',data)


def statewise(request):
    d=datetime.datetime.now(pytz.timezone('Asia/Kolkata'))
    url = 'http://corona-api.com/countries/{}'
        
    info = requests.get(url.format('IN')).json()
        
        
        
    country=info['data']
    response_india = requests.get('https://api.covid19india.org/data.json')
    
    india = response_india.json()    
    india1=india['statewise']
    india1_comma = ['active', 'confirmed', 'deaths','recovered' ,'deltaconfirmed', 'deltadeaths', 'deltarecovered', ]
    for x in india1:
        for l in india1_comma:
            total = x[l]
            total = format_currency(total, 'INR', locale='en_IN')
            total = total[1:len(total)-3]
            x[l] = total
    graph=india['cases_time_series']
    daywise={}
    for entry in graph:
        day = entry.pop('date')
        daywise[day] = entry
    l=len(daywise)
    l=l-1
    daywise = dict(list(daywise.items())[l:0: -10])


    daywise2 = dict(list(daywise.items())[::-1 ])
    
    
    


    data={
        'india':india1,
        'india_total':india['statewise'][0],
        'd':d,
        'daywise':daywise2,
        'info':country,
        
      
    }

    return render(request, 'covidapp/india.html',data)

def stateview(request,sname, scode):
    scode = scode.lower()
    if sname == 'Total':
        return redirect('statewise')
    else:    
        d=datetime.datetime.now(pytz.timezone('Asia/Kolkata'))
        state_timeline = requests.get('https://api.covid19india.org/states_daily.json').json()
        state_timeline = state_timeline['states_daily']
        zones = requests.get('https://api.covid19india.org/zones.json')
        zones = zones.json()
        zones = zones['zones']
        zone_name = {}
        for entry in zones:
            district_name = entry.pop('district')
            zone_name[district_name] = entry


        response_india = requests.get('https://api.covid19india.org/data.json')
        india = response_india.json()

        response_state=requests.get('https://api.covid19india.org/state_district_wise.json')
        districts= response_state.json()
        state=india['statewise']
        india1_comma = ['active', 'confirmed', 'deaths','recovered' ,'deltaconfirmed', 'deltadeaths', 'deltarecovered', ]
        for x in state:
            for l in india1_comma:
                total = x[l]
                total = format_currency(total, 'INR', locale='en_IN')
                total = total[1:len(total)-3]
                x[l] = total
        state=list(state)
        newstate={}
        for entry in state:
            name = entry.pop('state')
            newstate[name] = entry
        s=newstate[sname]
        dis=districts[sname]['districtData']

        for key,value in dis.items():
            for x in zone_name:
                if x == key:
                    dis[key]['zone'] = zone_name[x]['zone']
        deceased = []
        confirmed = []
        recovered = []
        for x in state_timeline:
            if x['status'] == 'Deceased':
                deceased.append(x[scode])  
            if x['status'] == 'Confirmed':
                confirmed.append(x[scode]) 
            if x['status'] == 'Recovered':
                recovered.append(x[scode])               

        data={
            's':s,
            'sname':sname,
            'scode':scode,
            'd':d,
            'dis':dis,
            'zone_name':zone_name,
            'state_timeline':state_timeline,
            'deceased':deceased,
            'confirmed':confirmed,
            'recovered':recovered
            
         
        }
       
        
    return render(request, 'covidapp/stateview.html',data)

    
def statesearch(request):
    
    statelist={'MH' : 'Maharashtra', 'TN' : 'Tamil Nadu', 'DL' : 'Delhi', 'GJ' : 'Gujarat', 'UP' : 'Uttar Pradesh', 'RJ' : 'Rajasthan', 'MP' : 'Madhya Pradesh', 'WB' : 'West Bengal', 'UN' : 'State Unassigned', 'KA' : 'Karnataka', 'HR' : 'Haryana', 'BR' : 'Bihar', 'AP' : 'Andhra Pradesh', 'JK' : 'Jammu and Kashmir', 'TG' : 'Telangana', 'OR' : 'Odisha', 'AS' : 'Assam', 'PB' : 'Punjab', 'KL' : 'Kerala', 'UT' : 'Uttarakhand', 'JH' : 'Jharkhand', 'CT' : 'Chhattisgarh', 'TR' : 'Tripura', 'HP' : 'Himachal Pradesh', 'GA' : 'Goa', 'MN' : 'Manipur', 'CH' : 'Chandigarh', 'PY' : 'Puducherry', 'LA' : 'Ladakh', 'NL' : 'Nagaland', 'MZ' : 'Mizoram', 'AR' : 'Arunachal Pradesh', 'ML' : 'Meghalaya', 'AN' : 'Andaman and Nicobar Islands', 'DN' : 'Dadra and Nagar Haveli and Daman and Diu', 'SK' : 'Sikkim', 'LD' : 'Lakshadweep' }
    
    state_list=list(statelist)

covid19/covidapp/templates/covidapp/about.html
{% extends 'covidapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
TraCOR - About Us
{% endblock title %}


{% block style %}
<style>
.btn-linkedin {
    background: #0E76A8;
    border-radius: 0;
    color: #fff;
    border-width: 1px;
    border-style: solid;
    border-color: #084461;
    border-radius:5px
}
.btn-linkedin:link, .btn-linkedin:visited {
    color: #fff;
}
.btn-linkedin:active, .btn-linkedin:hover {
    background: #084461;
    color: #fff;
}
.animate
{
	transition: all 0.1s;
	-webkit-transition: all 0.1s;
}

.action-button
{
	position: relative;
	padding: 3px 5px;
  margin: 0px 10px 10px 0px;
  float: left;
	border-radius: 10px;
	
	
	color: #FFF;
	text-decoration: none;	
}

.blue
{
	background-color: #3498DB;
	border-bottom: 5px solid #2980B9;
	text-shadow: 0px -2px #2980B9;
}

#id_suggestion{
    width: 60%;
    border-radius: 7px;
}

#id_rating{
    width: 60%;
    border-radius: 7px;
}

#id_email{
    width: 60%;
    border-radius: 7px;
}

</style>
{% endblock style %}
{% block content %}
<div class='container'>

    {% if messages %}
    <br>
    {% for x in messages %}
    <div class='alert alert-custom' style="background-color: #1d1d1d;font-weight: 450;"><center>{{x}}</center></div>
    {% endfor %}
   {% endif %}
   {% if form.errors %}
   <br>
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-custom" style="background-color: #1d1d1d;font-weight: 450;">
                <center>{{ error|escape }}</center>
                </div>   
            {% endfor %}
        {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-custom" style="background-color: #1d1d1d;font-weight: 450;">
        <center>{{ error|escape }}</center>
        </div>
    {% endfor %}
    {% endif %}
    <br>
    <div class='new_card col-12 animated animatedFadeInUp fadeInUp' style="animation-delay: 0.5s;">
       
    <center><h2 class='mt-3'><i class="fas fa-cogs"></i> Who made this website?</h2></center>
    <br><br>
    <ul style='list-style-type: disc'>
        <li>This website is made with <i class='fa fa-heart' style="color:red"></i> by <strong>Sanay Shah</strong> and <strong>Shivesh Jha</strong>.</li><br>
        <li>We are computer engineering students from Dwarkadas J Sanghvi College Of Engineering, Mumbai.</li><br>
        <li><a class='btn btn-linkedin' href='https://www.linkedin.com/in/sanay-shah-45b973194/'><i class="fab fa-linkedin-in"></i> @Sanay Shah</a>&ensp; <a class='btn btn-linkedin' href='https://www.linkedin.com/in/shivesh-jha-b74b46198/'><i class="fab fa-linkedin-in" aria-hidden="true"></i> @Shivesh Jha</a></li><br>
        <li>If you have any cool ideas to add to the website, fill in the suggestion form below or connect on LinkedIn.</li>
        </ul>
        <div class='text-muted' style='text-align: right;font-weight: 630;'><i class="fa fa-info-circle" aria-hidden="true"></i> {{count}} {% if count == 1 %}person has {% else %}people have {% endif %}rated this site so far.</div>
    </div>
    <br>
     <div class='new_card col-12 animated animatedFadeInUp fadeInUp' style="padding:20px;animation-delay: 1s;">
        <div class='col-12 '>
        <form method="POST" class="form-group">
            {% csrf_token %}
            <p>Suggestion/Comments (if any) :<br>{{form.suggestion}}</p><br>
                <p>Email<sup>*</sup> :<br>{{form.email}}</p><br>
                <p>Rating (Out of 5)<sup>*</sup> :<br>{{form.rating}}</p>
                
            <button class="btn btn-secondary"  type='submit' style="background-color: #1d1d1d;">Submit</button>
        </form>
        </div>
    </div>
    </div>
    
{% endblock content %}

covid19/covidapp/templates/covidapp/api.html
{% extends 'covidapp/base.html' %}


{% block title %}
TraCOR
{% endblock title %}


{% block style %}
<style>

  
      * {
      margin: 0;
    }

    

    #map {
      width: 100%;
      height: 70%;
    }


   
  .ta{
    margin-bottom: 30px;
  }
.my-custom-scrollbar {
position: relative;
height: 500px;
overflow: auto;
}
.table-wrapper-scroll-y {
display: block;
}


  body {
    padding: 0;
    margin: 0;
    height: 100vh;
    width: 100%;
    background: #121212;
}
.form-control:focus {
  box-shadow: none;
}

.form-control-underlined {
  border-width: 0;
  border-bottom-width: 1px;
  border-radius: 0;
  padding-left: 0;
}

</style>
{% endblock style %}







{% block content %}

<div class='card' style="background-color:rgb(31, 31, 31);margin:12px;padding: 12px;">
<strong style="letter-spacing: 1px;font-size: 12px;"><marquee onmouseover="stop()" onmouseout="start()">
  Top 3 countries with highest number of cases.&ensp;&ensp;1. {{1.name}} : {{1.latest_data.confirmed}}&ensp;&ensp;2. {{2.name}} : {{2.latest_data.confirmed}}&ensp;&ensp;3. {{3.name}} : {{3.latest_data.confirmed}}
</marquee>
</strong>
</div>

<br>

<div class="container">       

<center><form method="post" action="/search/" style="margin-top: ;">
  {% csrf_token %}
  <div class="p-1  shadow-sm md-4" style="border-radius: 24px;width:275px;background-color: #1d1d1d;border: 3px solid lightgray;">
    <div class="input-group">
      <input type="search" list="browsers" placeholder="Search state,country" onfocus="this.value=''" type="search" name="searchstate" aria-describedby="button-addon1" class="form-control border-0 " style="background-color: #1d1d1d;border-radius: 10px;color: whitesmoke;">
      <div class="input-group-append">
        <button id="button-addon1" type="submit" class="btn btn-link text-primary"><i class="fa fa-search" style="color: white;"></i></button>
      </div>
    </div>
  </div>
  <datalist id="browsers"  style="background-color: #121212;">
    {% for key,value in statelist.items %}
    <option value='{{value.statecode}}' style="background-color: #121212;">{{key}}</option>
    {% endfor %}
    {% for x in all_country %}
    <option value='{{x.code}}'>{{x.name}}</option>
    {% endfor %}
  </datalist>
  </form></center><br>
{% if messages %}
{% for x in messages %}
<center><span class='alert alert-custom text-muted' style="background-color: #121212;">{{x}}</span></center>
{% endfor %}
{% endif %}
</div>
<div class=" container" >
  <h5 class='kit animated animatedFadeInUp fadeInUp' style="text-align: center;font-weight: bold;margin:25px;color:white;animation-delay: 0.1s;"><i class='fas fa-globe-americas' style="padding: 12px;color: skyblue;"></i>GLOBAL <span style="color: bisque;">COVID19</span> STATS </h4><br>
  <div class=" row" style="text-align: center;padding-bottom:30px;">
    <div class=" col-4  animated animatedFadeInUp fadeInUp" style="animation-delay: 0.3s;">
      <h5 id="confirm" class="kit" style="color:rgba(93, 93, 255, 0.801);font-weight: bold;">{{global.totalConfirmed}}</h5>
      <p style="font-size: 15px;"><span class="count" style="color: rgb(160, 160, 253);">+[{{global.totalNewCases}}]</span></p><br>
      <p style="color: rgba(93, 93, 255, 0.801);font-size: 15px;font-weight: bold;">Confirmed</h1>
    </div>
    <div class="col-4  animated animatedFadeInUp fadeInUp" style="animation-delay: 0.5s;">
      <h5 class="kit" style="color: red;font-weight: bold;">{{global.totalDeaths}}</h5>
      <p style="font-size: 15px;"><span class="count" style="color: rgb(240, 133, 133);">+[{{global.totalNewDeaths}}]</span></p><br>
      <p style="color: red;font-size: 15px;font-weight: bold;">Deaths</h8>
    </div><br>
    <div class="col-4  animated animatedFadeInUp fadeInUp" style="animation-delay: 0.7s;">
      <h5 class="kit" style="color: green;font-weight: bold;">{{global.totalRecovered}}</h5>
      <p  style="font-size: 15px;"><span class="count" style="color: yellowgreen;"><i class="fa fa-heart" aria-hidden="true" style="padding: 5px;"></i></span></p><br>
      <p  style="color: green;font-size: 15px;font-weight: bold;">Cured</p>
    </div>
    

  </div>
  <div style="text-align: center;"><a style="animation-delay: 0.9s;" href={% url 'globalview' %} class="animated animatedFadeInUp fadeInUp" >Click for more info</a>
  </div><br>
    <div class="animated animatedFadeInUp fadeInUp" style="margin: 10px;margin-top: 20px;border-bottom: 1px solid lightgray;animation-delay: 1s;"></div>

</div><br><br>

<div class="container"  style="text-align: center; text-align: center;"> 
  
  <h5 class='kit animated animatedFadeInUp fadeInUp' style="text-align: center;font-weight: bold;color: white;animation-delay: 1.1s;"><i class="fa fa-viruses" style="padding: 12px;"></i><span style="color: bisque;">COVID19</span> IN INDIA</h5><br><br>
      
      <div class="row" style="padding-bottom:30px;">
          <div class=" col-3 animated animatedFadeInUp fadeInUp" style="animation-delay:1.2s;margin-bottom: 30px;">
            <h5 class='kit'><span class="counter " style="color: rgba(93, 93, 255, 0.801);font-weight: bold;">{{india_total.confirmed}}</span></h3>
            <p ><span class="counter" style="font-size: 12px;color:rgb(160, 160, 253); ">+[{{india_total.deltaconfirmed}}]</span></p><br>         
              <p style="font-size: 12px;font-weight: bold;color: rgba(93, 93, 255, 0.801);">Cases</p>
          </div>

          <div class="col-3 animated animatedFadeInUp fadeInUp" style="animation-delay:1.2s;margin-bottom: 30px;">
            <h5 class='kit'><span class="counter" style="color: rgb(203, 206, 10);font-weight: bold;">{{india_total.active}}</span></h1>
            <p ><span class="counter" style="font-size: 12px;color: rgb(203, 206, 10);"><i class="fa fa-heart" aria-hidden="true" style="padding-top: 5px;"></i></span></p><br>
              <p style="font-size: 12px;font-weight: bold;color: rgb(203, 206, 10);">Active</p>
          </div>

          <div class="col-3 animated animatedFadeInUp fadeInUp" style="animation-delay:1.3s;margin-bottom: 30px;"> 
            <h5 class='kit'><span class="counter" style="color: red;font-weight: bold;">{{india_total.deaths}}</span></h1>
            <p ><span class="counter" style="color: red;font-size: 12px;">+[{{india_total.deltadeaths}}]</span></p><br>                 
              <p   style="font-weight: bold;font-size: 12px;color: red;">Deaths</p> 
            </div>

          <div class="col-3 animated animatedFadeInUp fadeInUp" style="animation-delay:1.4s;margin-bottom: 40px;">
            <h5 class='kit'><span class="counter" style="color: green;font-weight: bold;">{{india_total.recovered}}</span></h1>
              <p style="font-size: 12px;"><span class="counter" style="color: green;">+[{{india_total.deltarecovered}}]</span></p><br>        
                <p style="font-size: 12px;font-weight: bold;color: green;">Cured</p>
          </div>
        <div class="container animated animatedFadeInUp fadeInUp" style="color: white;padding: 12px;animation-delay: 1.5s"><a href="/india/">Click here for statewise stats</a> </div>
        
        </div>
     
</div>
<div class='container'>
  <div class=" animated animatedFadeInUp fadeInUp" style="border-top: 1px solid lightgray;margin: 4px;animation-delay: 1.6s"></div>
</div>
<br><br>

<div class="container">
  <p class=" animated animatedFadeInUp fadeInUp" style="color:rgba(255, 255, 224, 0.767);font-weight: bold;text-align: center;animation-delay: 1.7s">Tap the marker for <span style="color: red;">COVID19</span> data in that particular country:</p><br>
    <div class=" animated animatedFadeInUp fadeInUp" id="map" style='animation-delay: 1.8s'></div><br><br>
</div>

<div class=" container animated animatedFadeInUp fadeInUp " style="animation-delay: 1.9s;">
<h3 style="font-weight: 600;">World</h2><br>
<center>
<div class="table-wrapper-scroll-y my-custom-scrollbar">
<table >
    <tr>
      <th class='sticky-top' style='text-align: left;'>Country</th>
      <th class='sticky-top' style='color:rgba(93, 93, 255, 0.801);font-weight:1000'>Confirmed</th>
      <th class='sticky-top' style="color: red;">Deaths</th>
      <th class='sticky-top' style="color: green;">Recovered</th>
      
    </tr>
      
    {% for value in all_country %}
    <tr>
      <td><p style='text-align: left;'><a href='/country/{{value.code}}/'>{{value.rank}}. {{value.name}}</a></p></td>
      <td><p ><span style='color: rgba(93, 93, 255, 0.801);'>{% if value.today.confirmed != 0 %}+{{value.today.confirmed}}{% endif %}</span> {{value.latest_data.confirmed}}</p></td>
      <td><p ><span style="color: red;">{% if value.today.deaths != 0 %}+ {{value.today.deaths}}{% endif %}</span> {{value.latest_data.deaths}}</p></td>
      <td><p ><span style="color: green;"> </span> {% if value.name == 'Spain' or value.name == 'UK' or value.name == 'Netherlands' or value.name == 'Sweden' and value.latest_data.recovered == '0' %}N/A{% else %}{{value.latest_data.recovered}}{% endif %}</p></td>
    </tr>
    {% endfor %}
  </table>
  </div>
</center>
</div></div><br>
      </div>


{% block script %}
<script>
  const coordinates = {
    Latitude:[ 
      {% for x in all_country %}
      '{{x.coordinates.latitude}}', 
      {% endfor %}
    ],
    Longitude: [
      {% for x in all_country %}
      '{{x.coordinates.longitude}}', 
      {% endfor %}
    ],
    name:[
        {% for x in all_country %}
        '{{x.name}}',
        {% endfor %}
    ],
    Cases:[
        {% for x in all_country %}
        '{{x.latest_data.confirmed}}',
        {% endfor %}
    ],
    Deaths:[
        {% for x in all_country %}
        '{{x.latest_data.deaths}}',
        {% endfor %}
    ],
    Recovered:[
        {% for x in all_country %}
        '{{x.latest_data.recovered}}',
        {% endfor %}
    ],
    code:[

        {% for x in all_country %}
        '{{x.code}}',
        {% endfor %}

    ]
  };
  
  var myIcon = L.icon({
    iconUrl: 'https://img.icons8.com/nolan/64/street-view.png',
    iconSize: [35, 45],

});
  const map = L.map('map').setView([20, 77], 3);
  
  var CartoDB_DarkMatter = L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', {
subdomains: 'abcd',
maxZoom: 19
}).addTo(map);

  for (let i = 0; i < Object.keys(coordinates.Latitude).length; i =i+ 1) {
    const marker = L.marker([
      coordinates.Latitude[i],
      coordinates.Longitude[i],
    ],{icon : myIcon});
    marker.myData = { id: coordinates.name[i] ,cases:coordinates.Cases[i],deaths:coordinates.Deaths[i],recovered:coordinates.Recovered[i]};
    marker.bindPopup("<p style='font-weight:800'>"+ marker.myData.id +"</p>"+"<p>"+ "Cases"+" : "+marker.myData.cases +"</p>"+"<p>"+"Deaths"+" : "+marker.myData.deaths +"</p>"+"<p>"+"Recovered"+" : "+marker.myData.recovered +"</p>");
    marker.on('mouseover',function(e){
      this.openPopup();
    });
    marker.on('mouseout',function(e){
      this.closePopup();
    });

    marker.addTo(map);
  }
</script>

{% endblock script %}

{% endblock content %}

covid19/covidapp/templates/covidapp/googlea18599f9d176b529.html
google-site-verification: googlea18599f9d176b529.html